version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tasktracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_tracker
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
